jobs:
  tests:
    run-on:
      - type: branch
        include-match: ^.*$
    script-defaults:
      template-environment-variables: true
    task-defaults:
      traits: [bash, ruby, firefox-esr, tightvnc]
    task:
      _cider-ci_include: cider-ci/test-task.yml

